[package]
name = "rustpflow"
version = "0.1.0"
authors = ["stackdump <myork@stackdump.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.53"

[profile.release]
lto = true
opt-level = 's'
